on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

name: RPM

jobs:
  build:
    name: Build ${{ matrix.triple.name }}
    strategy:
      matrix:
        triple:
          - {
            name: 'el8',
            image: 'registry.access.redhat.com/ubi8/ubi:8.6',
          }
    runs-on: ubuntu-latest
    container: ${{ matrix.triple.image }}
    steps:
      - name: Enable rocky appstream if ubi
        run: |
          grep -e "^Red Hat Enterprise Linux" /etc/redhat-release \
          && RELEASE=$(grep -oE "[0-9]+\.[0-9]+" /etc/redhat-release) \
          && printf "[rocky-$RELEASE-appstream]\nname=Rocky Linux $RELEASE - AppStream\nbaseurl=http://dl.rockylinux.org/pub/rocky/$RELEASE/AppStream/x86_64/os/\ngpgcheck=1\nenabled=1\ngpgkey=https://dl.rockylinux.org/pub/rocky/$RELEASE/AppStream/x86_64/os/RPM-GPG-KEY-rockyofficial\nincludepkgs=rpmdevtools,dbus-devel\n" > /etc/yum.repos.d/Rocky-"$RELEASE"-AppStream.repo \
          || true

      - name: Install basic rpmbuild toolchain
        run: |
          dnf install -y git rpm-build rpmdevtools dnf-plugins-core python3-pip cmake

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Generate the standalone spec file from the template and args
        run: |
          mkdir build
          cd build
          cmake ..
          cpack -G RPM

      - name: Export files
        run: |
          mv build/*.rpm /tmp

      - name: Archive RPMs
        uses: actions/upload-artifact@v2
        with:
          name: fapolicy-analyzer-rpms
          path: |
            /tmp/*.rpm

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ steps.tag_name.outputs.VERSION }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
          draft: true
          files: |
            /tmp/*.rpm
